require("randomizeR") #package necessary for "pbrpar" function in line 33, "genSeq" in line 34, and "getRandList" in line 35
require("stringr") #package necessary for "str_pad" function in line 31

#select run to begin prompts
schema <- function(){
  t <- readline("How many treatment sites to you have? ")
  s <- readline("How many subjects do you have at each site? ")  
  b <- readline("How many subjects are in each block? ")
  r <- readline("Specify a ratio for treatment to control t:c ")
  sd <- readline("Set a seed number for reproducibility ")
  
  t <- as.numeric(unlist(strsplit(t, ",")))  #t will represent number of sites
  s <- as.numeric(unlist(strsplit(s, ",")))  #s will represent number of subjects at each site
  b <- as.numeric(unlist(strsplit(b, ",")))  #b will represent the number of subjects in each block
  r <- (unlist(strsplit(r, ":")))            #ratio will be given in form t:c, need to get "t" and "c" separately
  n <- as.numeric(r[1])                      #n will represent number of treatments from ratio 
  d <- as.numeric(r[2])                      #d will represent number of controls from ratio 
  sd <- as.numeric(unlist(strsplit(sd, ",")))
  
  df1 <- data.frame(Site=character(), Subject=integer())  #create empty data frame
  sub<- seq(1:s) #list of subjects
  for (i in b) {
    blk<-s/b  #compute number of blocks
    if (s %% b !=0 | s %% t !=0 ){
      print("Enter valid parameter")    #if condition is not met, error message will occur
    }
  }
  
  sub<-str_pad(sub,width=2,side="left",pad="0") #to get #'s < 10 to be of the form "0#"
  bc<-rep(b,blk)    #vector that contains block size, number of blocks times
  ab<-pbrPar(bc, K = 2, ratio = c(n,d), groups = c("T","C"))  #function to randomly assign treatment and control using the appropriate ratio
  seq1<-genSeq(ab,t,seed=sd)   #get the random sequence generated by pbrPar function
  list1 <- getRandList(seq1)
  for (i in c(1:t)) {           #loop to create site names and data frame
      sites<-rep(LETTERS[i],3)           #repeat letters 3 times e.g. A A A
      sites<-paste(sites, collapse="")     #put letters together e.g. 'AAA'
      tempdf <- data.frame(Site=as.vector(rep(sites, length(sub))),   
                           Subject=as.vector(sub))    #create temporary data frame to store values during loop
      df1 <- rbind(df1, tempdf)   #combine empty data frame with temporary data frame
  }
  
  df1$Condition=as.vector(t(getRandList(seq1)))  #add a new column to the data frame
  print(df1)    #print the schema
  write.csv(df1, file = "Schema.csv")
}

schema()   #prompts will begin
